version: '3.8'
services:
  waha:
    restart: always
    image: devlikeapro/waha:latest
    container_name: waha
    dns:
      - 1.1.1.1
      - 8.8.8.8

    logging:
      driver: 'json-file'
      options:
        max-size: '100m'
        max-file: '10'

    volumes:
      - './sessions:/app/.sessions'
      - './media:/app/.media'

    env_file:
      - .env

    depends_on:
      db:
        condition: service_healthy

    networks:
      - server

  db:
    image: postgres:latest
    container_name: postgresql
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data
    command:
      - postgres
      - '-c'
      - 'max_connections=3000'
    logging:
      driver: 'json-file'
      options:
        max-size: '100m'
        max-file: '10'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - server

  app:
    build: .
    container_name: backend
    env_file:
      - .env
    ports:
      - '3000:8000'
    depends_on:
      db:
        condition: service_healthy
      waha:
        condition: service_started
    command: sh -c "npx prisma migrate deploy && npx prisma generate && npm run start:prod"
    networks:
      - server

networks:
  server:
volumes:
  pg_data: {}
